version: "3.1"
services:

    mysql:
      image: mariadb:10
      container_name: ${APP_NAME}-db
      command: mysqld --innodb-flush-method=fsync
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      volumes:
        - ./docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
        - ./docker/mysql/data:/var/lib/mysql

    redis:
      image: redis:alpine
      container_name: ${APP_NAME}-cache
      command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
      environment:
        - REDIS_PORT=${REDIS_PORT}
      volumes:
        - ./docker/redis/data:/data

    php-fpm:
      build: docker/php-fpm
      container_name: ${APP_NAME}-php
      working_dir: /application
      volumes:
        - .:/application
        - ./vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64:/usr/local/bin/wkhtmltopdf
        - ./docker/php-fpm/php-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      links:
        - mysql:${DB_HOST}
        - redis:${REDIS_HOST}

    nginx:
      image: nginx:alpine
      container_name: ${APP_NAME}-http
      working_dir: /application
      volumes:
          - .:/application
#          - ./vendor/h4cc/wkhtmltoimage-amd64/bin:/usr/bin
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params
      ports:
       - "8888:80"
      links:
        - php-fpm:${APP_NAME}-php

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: ${APP_NAME}-phpmyadmin
      environment:
        PMA_HOST: ${DB_HOST}
        PMA_PORT: 3306
        UPLOAD_LIMIT: 300M
      ports:
        - '8050:80'
      volumes:
        - /sessions
